---
title: "Getting to know .mono[R]"
subtitle: "EC 425/525, Lab 1"
author: "Edward Rubin"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
exclude: true

```{R, setup, include = F}
# devtools::install_github("dill/emoGG")
library(pacman)
p_load(
  broom, tidyverse,
  latex2exp, ggplot2, ggthemes, ggforce, viridis, extrafont, gridExtra,
  kableExtra, snakecase, janitor,
  data.table, dplyr, estimatr,
  lubridate, knitr, parallel,
  lfe,
  here, magrittr
)
# Define pink color
red_pink <- "#e64173"
turquoise <- "#20B2AA"
orange <- "#FFA500"
red <- "#fb6107"
blue <- "#3b3b9a"
green <- "#8bb174"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
purple <- "#6A5ACD"
slate <- "#314f4f"
# Dark slate grey: #314f4f
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  warning = F,
  message = F
)
opts_chunk$set(dev = "svg")
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
options(knitr.table.format = "html")
```

```{R, plotting, include = F}
theme_axes <- theme_void() + theme(
  text = element_text(family = "Fira Sans Book"),
  axis.title = element_text(size = 18),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
```

---
# Exercises

1. Using the tools we've covered, generate a dataset $\left( n=50 \right)$ such that
$$
\begin{align}
  y_i = 12 + 1.5 x_i + \varepsilon_i
\end{align}
$$
where $x_i\sim N(3,7)$ and $\varepsilon_i\sim N(0,1)$.

2. Estimate the relationship via OLS using only matrix algebra. Recall
$$
\begin{align}
  \hat{\beta}_\text{OLS} = \left( {X}^\prime {X} \right)^{-1} {X}^\prime {y}
\end{align}
$$

3. .hi-slate[*Harder*] Write a function that estimates OLS coefficients using matrix algebra. Compare your results with the canned function from .mono[R] (`lm`).

4. .hi-slate[*Hardest*] Bring it all together: Use your DGP (1) and function (3) to run a simulation that illustrates the unbiasedness of OLS.
---
layout: true

# Example solution: Part 1

1\. Using the tools we've covered, generate a dataset $\left( n=50 \right)$ such that
$$
\begin{align}
  y_i = 12 + 1.5 x_i + \varepsilon_i
\end{align}
$$
where $x_i\sim N(3,7)$ and $\varepsilon_i\sim N(0,1)$.

---

.pull-left[.pseudocode-small[
1. Set seed
1. Set sample size n=50
1. Generate x~N(3,7)
1. Generate ε~N(0,1)
1. Calculate y<br>y ≔ 12 + 1.5 x + ε
]]

--

.pull-right[
```{R, sol1}
# Set seed
set.seed(12345)
# Set sample size
n <- 50
# Generate x~N(3,7)
x <- rnorm(
  n = n, mean = 3, sd = sqrt(7)
)
# Generate ε~N(0,1)
ε <- rnorm(n = n)
# Calcualte y
y <- 12 + 1.5 * x + ε
```
]
---
layout: false
class: clear, center, middle

```{R, plot1, echo = F}
ggplot(data = data.frame(x, y), aes(x, y)) +
  geom_point(color = "darkslategrey", alpha = 0.85, size = 3) +
  theme_pander(base_size = 18, base_family = "Fira Sans Book") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
```
---
layout: true

# Example solution: Part 2

2\. Estimate the relationship via OLS using only matrix algebra. Recall
$$
\begin{align}
  \hat{\beta}_\text{OLS} = \left( {X}^\prime {X} \right)^{-1} {X}^\prime {y}
\end{align}
$$

---

.pull-left[.pseudocode-small[
1. Convert y to matrix
2. Create X matrix: [1 x]
3. OLS matrix math
]]
--
.pull-right[
```{R, sol2}
# Convert y to matrix
y_m <- as.matrix(y)
# Create X matrix
X_m <- cbind(1, x)
# Matrix math
XX <- t(X_m) %*% X_m
Xy <- t(X_m) %*% y_m
b_ols <- solve(XX) %*% Xy
```
]

--

- `cbind` is *column-binding* its arguments (`1` and `x`).

--
- .slate[*Alternatives:*]
  - `matrix(data = c(rep(1, n), x), ncol = 2, byrow = F)`
  - `as.matrix(data.frame(1, x))`

---

How did we do?
--

.pull-left[
.hi-pink[Our estimates:]
```{R, sol2_est}
b_ols
```
]
--
.pull-right[
.hi-purple[.mono[R]'s estimates:]
```{R, sol2_lm}
lm(y ~ x)
```

]
---
layout: false
class: clear, center, middle

```{R, sol2_plot, echo = F}
ggplot(data = data.frame(x, y), aes(x, y)) +
  geom_abline(intercept = b_ols[1,1], slope = b_ols[2,1], color = red_pink, size = 1.25, alpha = 0.85) +
  geom_point(color = "darkslategrey", alpha = 0.85, size = 3) +
  theme_pander(base_size = 18, base_family = "Fira Sans Book") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
```
---
exclude: true

```{R, generate pdfs, include = F, eval = T}
source("../../ScriptsR/unpause.R")
unpause("01RBasics.Rmd", ".", F, T)
```
