---
title: "Project Proposal"
subtitle: "Step 2"
author: "**EC 425/525:** Econometrics"
date: "<br>Due *before* midnight (11:59pm) on .bold[Thursday, 30 May 2019]"
seal: false
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

```{R, setup, include = F}
# Packages
library(pacman)
p_load(
  ggplot2, gridExtra, ggthemes, latex2exp, kableExtra,
  tidyverse, broom, knitr, magrittr
)
# Colors
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
# Themes
theme_axes_y <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.y = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_x <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.x = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 11))
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  warning = F,
  message = F
)
```

.mono.b[DUE] Your .b[typed] proposal is due *before* 11:59pm on Thursday, 30 May 2019 on [Canvas](https://canvas.uoregon.edu/).

Your grade will depend upon your ability to clearly respond to the assignment—concepts *and* constraints.

.mono.b[Assignment] Submit a project proposal that

1\. Motivates and outlines your .hi[*causal* question] of interest.
<br>
2\. Explains .hi[potential sources of selection] that could lead to bias.
<br>
3\. Describes the .hi[ideal experiment] which one could use to answer this question
<br>
4\. Discusses a .hi[practical research design] through which one could answer the original question—clarifying *how* this research design avoids selection bias.

.hi[Note] Your question must be caual in nature. If it is not, come up with a new question.

.mono.b[Sections] Your proposal requires the following sections/components. Separate them.

.mono.b[Title] (1 ≤ words ≤ 15)
<br>A title that clearly describes your question—and potentially how you would answer it.

.mono.b[Abstract] (50 ≤ words ≤ 150)
<br>A brief description of your project. Clearly describe the main question, how you will answer it, and why/for whom the results matter. Be concise and clear. You hook the reader here and elaborate later.

.mono.b[Question and motivation] (100 ≤ words ≤ 300)
<br> Explain why this area of research is interesting/important in general (not just to you). Why should your reader care/keep reading? After you .b[briefly] motivate the general topic, clearly describe your specific .b[causal question]. If necessary, motivate the specific question too.

.mono.b[Selection] (100 ≤ words ≤ 300)
<br> Why is this question challenging to answer empirically? In other words, what sources of selection bias concern you? If we simply run a regression of $y$ on $X$, why might $\hat{\beta}$ be biased?

.mono.b[Ideal experiment] (100 ≤ words ≤ 300)
<br> Describe the ideal experiment that would answer your question. This *ideal* experiment does not need to be practical—*i.e.*, you do not need to be able to run it in real life.

.mono.b[Practical research design] (100 ≤ words ≤ 400)
<br> How might you causally answer the your question in *real life*? Which data would you need? What sort of research design would you apply—selection on observables (regression with many controls, matching, propensity-score methods, *etc.*) or selection on observables (IV, RD, *etc.*)? How does this proposed research design avoid selection bias?

.mono.b[Update] Now that you've worked through these components, rewrite your abstract and title.


```{R, generate pdfs, include = F, eval = T}
system("decktape remark Step2.html Step2.pdf --chrome-arg=--allow-file-access-from-files")
```
