---
title: "Problem Set 2"
subtitle: "Operation IV"
author: "**EC 425/525:** Econometrics"
date: "<br>Due *before* midnight (11:59pm) on .bold[Wednesday, 29 May 2019]"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

```{R, setup, include = F}
# Packages
library(pacman)
p_load(
  ggplot2, gridExtra, ggthemes, latex2exp, kableExtra,
  tidyverse, broom, knitr, magrittr
)
# Colors
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
# Themes
theme_axes_y <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.y = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_x <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.x = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 11))
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  warning = F,
  message = F
)
```

.mono.b[DUE] Your solutions to this problem set are due *before* 11:59pm on Wednesday, 29 May 2019 on [Canvas](https://canvas.uoregon.edu/).
<br>Your problem set .hi[must be typed] with .mono[R] code beneath your responses. _E.g._,  [`knitr`](https://yihui.name/knitr/) and [`R Markdown`](https://rmarkdown.rstudio.com).

.mono.b[OBJECTIVE] We're going to walk through three classic applications of instrumental variables/two-stage least squares: endogeneity, measurement error, and randomized encouragement designs (REDs).

### Part 1: Selection bias

As this problem follows one from Wooldridge, we'll use the `wooldridge` package. You need to install the `wooldridge` package and then load the birthweight data using `data("bwght")`. For (limited) information on the variables, see the help file (_i.e._, `?wooldridge::bwght`).

.mono.b[1.01] We want to better understand the effect of a number of variables on birth weight (`bwght`)—namely gender (`male`), birth order (`parity`), income (`faminc`), and cigarette smoking during pregnancy (`packs`), _i.e._,
$$
\begin{align}
  \log(\text{bwght}_i) = \beta_0 + \beta_1 \text{male}_i + \beta_2 \text{parity}_i + \beta_3 \log(\text{faminc}_i) + \beta_4 \text{packs}_i + u_i
\end{align}
$$

.mono.b[1.01] Why might you expect amount of smoking (`packs`) to be correlated with $u_i$?

.mono.b[1.02] Suppose that you have data on average cigarette prices in each woman’s state of residence. Discuss whether this information is likely to satisfy the properties of a good instrumental variable for `packs`.

.mono.b[1.03] Use the data in in `bwght` to estimate equation the equation above. First, use OLS. Then, use 2SLS, where `cigprice` is an instrument for `packs`. Discuss any important differences in the OLS and 2SLS estimates.

.mono.b[1.04] Estimate the reduced form for `packs`. Does it raise any issues? What bearing does this conclusion have on your answer from .mono.b[1.03]?

### Part 2: Randomized encouragement designs

Another common implementation of IV/2SLS is a randomized encouragement design (RED), in which we randomly select individuals to receive "encouragement" (_e.g._, we call them to tell them about an exciting new program) in order to try to induce an exogenous change in program participation.

Let's imagine we want estimate the effect of solar-panel installation on household electricity consumption.

.mono.b[2.01] What would be the problem with comparing average electricity consumption for houses with solar panels to average electricity consumption without solar panels?

.mono.b[2.02] We randomly select 200 homes that have not yet installed solar panels. Within this sample, we randomly assign 100 houses to our "encouragement" group and 100 houses to our "non-encouragement" group. For the 100 houses in the encouragement group, we call/visit the households and tell them how awesome solar panels are—and how much money they could save with solar..super[.pink[†]]

.footnote[
.pink[†] Tangent: In case you haven't seen it, you should check out Google's [Project Sunroof](https://www.google.com/get/sunroof).
]

What do we need for our encouragement to be a valid instrument for solar panel installation? Do you think it is satisfied?

---
class: clear

.mono.b[2.03] A year later, we conduct a survey and find that in the encouragement group, 15/100 homes now have solar panels. In the non-encouragement group, 5/100 homes now have solar panels. If we estimated the first stage, (regressing an indicator for solar panel on an intercept and an indicator for encouragement group), what would our estimates be?

.mono.b[2.04] Imagine that average monthly electricity consumption in the encouragement group is 900 kWh (kilowatthours), while the average in the non-encouragement is 870 kWh. Based upon these numbers, what are the reduced-form (the effect of encouragement on energy consumption) and 2SLS estimates?

.mono.b[2.05] What does the LATE in this setting mean—_i.e._, what does *local* mean in this setting?

### Part 3: Measurement error

Now for a good, old-fashioned simulation.

.mono.b[3.01] Set up a data-generating process such that
$$
\begin{align}
  y_i = 3 + 7 x_i + u_i
\end{align}
$$
where $x_i\overset{\text{iid}}{\sim}N(5,5)$ and $u_i\overset{\text{iid}}{\sim}N(0,3)$.

In this simulation, we want to imagine what would happen if we could not observe $x_i$ (or if $x_i$ is measured with error/noise).

Thus, we want to create two additional variables: $w_{1i}$ and $w_{2i}$, such that
$$
\begin{align}
  w_{1i} &= x_i + \varepsilon_i \\
  w_{2i} &= x_i + \nu_i
\end{align}
$$
where $\varepsilon_i$ is i.i.d. standard Normal and $\nu_i$ is i.i.d. $N(0,7)$. For this problem, the sample size will be 50.

This setting is *classical* measurement error—the error (or noise) in measurement (_i.e._, $\varepsilon_i$ and $\nu_i$) is uncorrelated with the true variable $\left( x_i \right)$.

.it[Note:] No results for this part of the problem. Just make sure you've set up the DGP.

.mono.b[3.02] Imagine you cannot observe $x_i$ and are stuck with our noisily measured versions $w_{1i}$ and/or $w_{2i}$. Regress $y_i$ on $w_{1i}$. What do you get? What if you regress $y_i$ on both $w_{1i}$ *and* $w_{2i}$?

.mono.b[3.03] Now what happens if you *instrument* $w_{1i}$ with $w_{2i}$?

.mono.b[3.04] Confirm your results form .mono.b[3.02] and .mono.b[3.03] were not anomalies. In other words, run a simulation (with at least 1,000 iterations). In each iteration, record the results of

- regressing $y_i$ on $w_{1i}$
- regressing $y_i$ on $w_{2i}$
- instrumenting $w_{1i}$ with $w_{2i}$
- instrumenting $w_{2i}$ with $w_{1i}$

Report the results of your simulation. Do you see anything interesting? Does IV outperform OLS in the presence of measurement error (in terms of bias in $\hat{\beta}_1$)? What happens in your inference (look at the share of estimates in which you reject the null)?

---
class: clear

.mono.b[3.05] Now let $x_i$ .b[positively] correlate with $\varepsilon_i$ and .b[negatively] correlate with $\nu_i$, _i.e._, $\mathop{\text{Cov}} \left( x_i,\, \varepsilon_i \right) = 1$ and $\mathop{\text{Cov}} \left( x_i,\, \nu_i \right) = -2$. What happens to your results from .mono.b[3.04]?

*Hint* You can use `mvrnorm()` from `MASS` to draw correlated variables from a multivariate Normal distribution (which you can assume here). See our simulation lab for details.

.b[Extra credit] For our simple linear regression setup, show (analytically) why OLS estimates for $\beta_1$ are biased toward zero. How does IV help?

```{R, generate pdfs, include = F, eval = T}
system("decktape remark ps02.html ps02.pdf --chrome-arg=--allow-file-access-from-files")
```
